pro_final/home/urls.py
from django.contrib import admin
from django.urls import path
from home import views


app_name='home'
urlpatterns = [
    path('',views.home, name='Home'),
    path('about/',views.about, name='about'),
]

pro_final/perfil/urls.py
from django.urls import path

from perfil import views


app_name='perfil'
urlpatterns = [
    path('<int:id>', views.datos_del_perfil, name='perfil'),
    
]

pro_final/pro_final/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('movies/', include('movies.urls')),
    path('user/', include('user.urls')),
    path('perfil/', include('perfil.urls')),
    path('series/', include('series.urls')),
    ]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pro_final/user/urls.py
from django.urls import path

from user import views


app_name='user'
urlpatterns = [
    path('login', views.login_request, name='user-login'),
    path('logout', views.logout_request, name='user-logout'),
    path('register', views.register, name='user-register'),
    path('register/update', views.user_update, name='user-update'),
    path('avatar/load', views.avatar_load, name='avatar-load'),
    #path('password/update', views.password_update, name='password-update'),
]

pro_final/perfil/views.py
from django.shortcuts import render
from user.models import User, Avatar

def get_avatar_url_ctx(request):
    avatars = Avatar.objects.filter(user=request.user.id)
    if avatars.exists():
        return {"url": avatars[0].image.url}
    return {}

def datos_del_perfil(request, id):
    avatar_ctx = get_avatar_url_ctx(request)
    context_dict = {**avatar_ctx}
    user = User.objects.get(pk=id)
    context_dict.update({
        'user': user,
    })
    print('context_dict: ', context_dict)
    return render(
        request=request,
        context=context_dict,
        template_name="perfil/perfil.html"
    )

pro_final/perfil/templates/perfil/perfil.html
{% extends "home/index.html" %}
{% load static %}

{% block changingContent %}
<div>
    <h1>Perfil</h1>
    <hr></hr>
        <img height="160px" src="{{url}}" alt="">
        <h5><a style="color: rgb(3, 36, 184)" href="{% url 'user:avatar-load' %}">Cambiar Avatar</a></h5>
        <p><h3>Nombre de usuario: {{ user.username }}</h3></p>
        <p><h3>Nombre: {{ user.first_name }}</h3></p>
        <p><h3>Apellido: {{ user.last_name }}</h3></p>
        <p><h3>Email: {{ user.email }}</h3></p>
        <a class="btn btn-secondary" href="{% url 'user:user-update' %}">Editar usuario</a>
</div>
{% endblock %}