pro_final/home/urls.py
from django.contrib import admin
from django.urls import path
from home import views


app_name='home'
urlpatterns = [
    path('',views.home, name='Home'),
    path('about/',views.about, name='about'),
]

pro_final/movies/urls.py
from django.urls import path

from movies import views


app_name='movies'
urlpatterns = [
    path('', views.MoviesListView.as_view(), name='movies-list'),
    path('movies/add/', views.MoviesCreateView.as_view(), name='movies-add'),
    path('movies/<int:pk>/detail', views.MoviesDetailView.as_view(), name='movies-detail'),
    path('movies/<int:pk>/update', views.MoviesUpdateView.as_view(), name='movies-update'),
    path('movies/<int:pk>/delete', views.MoviesDeleteView.as_view(), name='movies-delete'),
    path('search', views.search, name='search'),
    path('movies/<int:pk>/comment/', views.AddCommentView.as_view(), name='add-comment'),
]

pro_final/pro_final/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('movies/', include('movies.urls')),
    path('user/', include('user.urls')),
    path('perfil/', include('perfil.urls')),
    path('series/', include('series.urls')),
    ]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pro_final/movies/models.py
from django.db import models

# Create your models here.
class Movies(models.Model):
    name = models.CharField(max_length=40)
    release_date = models.DateField()
    director_name = models.CharField(max_length=40)
    description = models.TextField(blank= True, null=True)

    def __str__(self):
        return f'{self.name}'

class Comment(models.Model):
    post = models.ForeignKey(Movies,on_delete=models.CASCADE,related_name='comments')
    name = models.CharField(max_length=80)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return f'Comentario: {self.body} \n comentado por: {self.name}'

pro_final/movies/forms.py
from django import forms
from pro_final.widget import DatePickerInput
from django.forms import ModelForm
from movies.models import Comment

class MoviesForm(forms.Form):
    name = forms.CharField(max_length=40, label='Nombre')
    release_data = forms.DateField(widget=DatePickerInput)
    director_name = forms.CharField(max_length=40, label='Nombre del director')
    description = forms.CharField(max_length=100, label='Descripción')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'body')

pro_final/movies/views.py
from venv import create
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from movies.models import Movies, Comment
from django.db.models import Q
from movies.forms import CommentForm
from pro_final.widget import DatePickerInput

# Create your views here.
class MoviesListView(ListView):
    model = Movies
    template_name = "movies/movies_list.html"


def search(request):
    if request.method == "POST":
        searched = request.POST['searched']
        movies = Movies.objects.filter(name__contains=searched)
    
        return render(
            request=request,
            context={'searched': searched, 'movies': movies},
            template_name="movies/movies_search.html",
        )
    else:
        return render(
            request=request,
            context={},
            template_name="movies/movies_search.html",
        )


class MoviesDetailView(DetailView):
    model = Movies
    template_name = "movies/movies_detail.html"
    fields = ['name', 'release_date', 'director_name', 'description']
    


class MoviesCreateView(LoginRequiredMixin, CreateView):
    model = Movies
    success_url = reverse_lazy('movies:movies-list')
    fields = ['name', 'release_date', 'director_name', 'description']


class MoviesUpdateView(LoginRequiredMixin, UpdateView):
    model = Movies
    success_url = reverse_lazy('movies:movies-list')
    fields = ['name', 'release_date', 'director_name', 'description']
    widgets = {
        'release_date': DatePickerInput,
    }


class MoviesDeleteView(LoginRequiredMixin, DeleteView):
    model = Movies
    success_url = reverse_lazy('movies:movies-list')


class AddCommentView(LoginRequiredMixin, CreateView):
    model = Comment
    form_class = CommentForm
    template_name = 'movies/add_comment.html'
    success_url = reverse_lazy('movies:movies-list')


    def form_valid(self, form):
        form.instance.post_id = self.kwargs['pk']
        return super().form_valid(form)

pro_final/movies/templates/movies/add_comment.html
{% extends "home/index.html" %}
{% load static %}

{% block changingContent %}
<h1>Agregar comantario</h1>
<br><br>
<div>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-primary" value="Comentar" />
    </form>
</div>
{% endblock %}

pro_final/movies/templates/movies/movies_confirm_delete.html
{% extends "home/index.html" %}
{% load static %}

{% block changingContent %}

<h2>Eliminar Pelicula</h2>
<hr></hr>

<p>Estás seguro de eliminar el Pelicula: {{ movies.name }}?</p>

<form action="" method="POST">
    {% csrf_token %}
    <input class="btn btn-primary text-uppercase" type="submit" value="Si, eliminar.">
    <a class="btn btn-primary text-uppercase" href="{% url 'movies:movies-list' %}" >Cancelar</a>
</form>

{% endblock %}

pro_final/movies/templates/movies/movies_detail.html
{% extends "home/index.html" %}
{% load static %}

{% block changingContent %}

<h2>Detalle de la Pelicula</h2>
<hr></hr>
<p><h3>Nombre: {{ movies.name }}</h3></p>
<p><h3>fecha de estreno: {{ movies.release_date }}</h3></p>
<p><h3>Nombre del director: {{ movies.director_name }}</h3></p>
<h4>Descripción:</h4>
<p><textarea readonly rows="7" cols="90" >{{ movies.description }}</textarea></p>
<p><a class="btn btn-primary" href="{% url 'movies:add-comment' movies.id %}">Comentar</a></p>
<div>
    <div>
        <h3>Comentarios</h3>
    </div>
    {% if not movies.comments.all %}
            Ningun comentario aun...
    {% else %}
            {% for coment in movies.comments.all %}
                <br>
                <p><h4>{{coment.body}}</h4></p>
                <h5>{{coment.name}} / {{coment.created_on}}</h5>
                <hr>
            {% endfor %}
        {% endif %}
</div>
<p><a class="btn btn-primary" href="{% url 'movies:movies-list' %}">Regresar a la lista de peliculas</a></p>

{% endblock %}

pro_final/movies/templates/movies/movies_form.html
{% extends "home/index.html" %}
{% load static %}

{% block changingContent %}
<h2>Formulario para guardar/editar Pelicula</h2>
<hr></hr>

<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-primary" value="Guardar Pelicula" />
</form>
{% endblock %}

pro_final/movies/templates/movies/movies_list.html
{% extends "home/index.html" %}
{% load static %}

{% block changingContent %}
<h1>Peiculas</h1>
{% if user.is_superuser %}
<a class="btn btn-primary text-uppercase" href="{% url 'movies:movies-add' %}">Agregar Pelicula</a>
{% endif %}
<hr></hr>
<form action="{% url 'movies:search' %}" method="POST">
    <div>
        {% csrf_token %}
        <input type="search" name="searched" placeholder="Buscar Peiculas">
        <button type="submit">Buscar</button>
        <a style="color: blue" href="{% url 'movies:movies-list' %}"><i class="fa fa-undo"></i></a>
    </div>

</form>

<ul>
    {% if movies_list %}
    {% for movies in movies_list %}
    <li>
        {{movies.name}}
        (
            <a href="{% url 'movies:movies-detail' movies.id %}">
                <i class="fa fa-eye" style="color: rgb(0, 0, 255);"> </i>
            </a>
        {% if user.is_superuser %}
        |
        <a href="{% url 'movies:movies-update' movies.id %}">
            <i class="fa fa-pencil" style="color: rgb(0, 0, 190);"> </i>
        </a>
        |
        <a href="{% url 'movies:movies-delete' movies.id %}">
            <i class="fa fa-trash" style="color: rgb(214, 6, 6);"> </i>
        </a>
        {% endif %}
        )
    </li>
    {% endfor %}
    {% else %}
        <p>No hay niguna pelicula cargada</p>
    {% endif %}
</ul>

{% endblock %}

pro_final/movies/templates/movies/movies_search.html
{% extends "home/index.html" %}
{% load static %}

{% block changingContent %}
    <div>
        {% if searched %}
            <h1>Estos son los resultados de "{{ searched }}"</h1>
            <br><br>
            <ul>
                {% for movie in movies %}
                <li>
                    {{movie.name}}
                    (
                        <a href="{% url 'movies:movies-detail' movie.id %}">
                            <i class="fa fa-eye" style="color: rgb(0, 0, 255);"> </i>
                        </a>
                {% if user.is_superuser %}
                |
                <a href="{% url 'movies:movies-update' movie.id %}">
                    <i class="fa fa-pencil" style="color: rgb(0, 0, 190);"> </i>
                </a>
                |
                <a href="{% url 'movies:movies-delete' movie.id %}">
                    <i class="fa fa-trash" style="color: rgb(214, 6, 6);"> </i>
                </a>
                {% endif %}
                )
                </li>
                {% endfor %}
            </ul>
            <p class="btn btn-secondary"><a href="{% url 'movies:movies-list'%}">Regresar..</a></p>
        {% else %}
            <h1>No buscaste nada</h1>
        {% endif %}
    </div>
{% endblock %}