pro_final/home/urls.py
from django.contrib import admin
from django.urls import path
from home import views


app_name='home'
urlpatterns = [
    path('',views.home, name='Home'),
    path('about/',views.about, name='about'),
]

pro_final/movies/urls.py
from django.urls import path

from movies import views


app_name='movies'
urlpatterns = [
    path('', views.MoviesListView.as_view(), name='movies-list'),
    path('movies/add/', views.MoviesCreateView.as_view(), name='movies-add'),
    path('movies/<int:pk>/detail', views.MoviesDetailView.as_view(), name='movies-detail'),
    path('movies/<int:pk>/update', views.MoviesUpdateView.as_view(), name='movies-update'),
    path('movies/<int:pk>/delete', views.MoviesDeleteView.as_view(), name='movies-delete'),
    path('search', views.search, name='search'),
    path('movies/<int:pk>/comment/', views.AddCommentView.as_view(), name='add-comment'),
]

pro_final/perfil/urls.py
from django.urls import path

from perfil import views


app_name='perfil'
urlpatterns = [
    path('<int:id>', views.datos_del_perfil, name='perfil'),
    
]

pro_final/pro_final/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('movies/', include('movies.urls')),
    path('user/', include('user.urls')),
    path('perfil/', include('perfil.urls')),
    path('series/', include('series.urls')),
    ]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pro_final/series/urls.py
from django.urls import path

from series import views


app_name='series'
urlpatterns = [
    path('series/', views.SeriesListView.as_view(), name='series-list'),
    path('series/add/', views.SeriesCreateView.as_view(), name='series-add'),
    path('series/<int:pk>/detail', views.SeriesDetailView.as_view(), name='series-detail'),
    path('series/<int:pk>/update', views.SeriesUpdateView.as_view(), name='series-update'),
    path('series/<int:pk>/delete', views.SeriesDeleteView.as_view(), name='series-delete'),
    path('search', views.search, name='search'),
    path('series/<int:pk>/comment/', views.AddCommentView.as_view(), name='add-comment'),
]

pro_final/user/urls.py
from django.urls import path

from user import views


app_name='user'
urlpatterns = [
    path('login', views.login_request, name='user-login'),
    path('logout', views.logout_request, name='user-logout'),
    path('register', views.register, name='user-register'),
    path('register/update', views.user_update, name='user-update'),
    path('avatar/load', views.avatar_load, name='avatar-load'),
    #path('password/update', views.password_update, name='password-update'),
]

pro_final/home/models.py
from django.db import models

# Create your models here.

pro_final/home/views.py
import imp
from django.shortcuts import render
from perfil.views import get_avatar_url_ctx

# Create your views here.
def home(request):
    avatar_ctx = get_avatar_url_ctx(request)
    context_dict = {**avatar_ctx}
    print('context_dict: ', context_dict)
    return render(
        request=request,
        context=context_dict,
        template_name="home/home.html"
    )


def about(request):
    return render(request, 'home/about.html')

pro_final/home/templates/home/about.html
{% extends "home/index.html" %}
{% load static %}

{% block changingContent %}
    <h1>Acerca de mí</h1>
    <div>
        <p>Hola!!! <br><br>
            Mi nombre es Agustin Peña, tengo 22 años y estoy aprendiendo a programar. <br>
            Me empecé a interesar en el mundo de la programación hace unos años por unos videos que vi en YouTube y quede fascinado, pero no tenía tiempo para practicarlo ya que estaba estudiando agronomía en la universidad nacional de Córdoba y no me daban los tiempos. <br>
            Hace unos meses casi un año fue cuando me puse las pilas con la programación y me vi unos videos acerca de python y desarrollo web, ahí fue cuando decidí inscribirme en este curso del cual aprendí un montón como podrán ver en la página que están situados. 
            </p>
    </div>
{% endblock %}

pro_final/home/templates/home/home.html
<!DOCTYPE html>
<html lang="es">
    <head>
        {% load static %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Nebula Blog </title>
        <link rel="icon" type="image/x-icon" href="{% static 'home/assets/palomitas-de-maiz.png' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'home/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'home:Home' %}"> Nebula Blog</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'home:Home' %}">Inicio</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'home:about' %}">Sobre mí</a></li>
                        {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'movies:movies-list' %}">Peliculas</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'series:series-list' %}">Series</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'perfil:perfil' user.id %}">Perfil</a></li>
                        <li><a class="btn btn-secondary" href="{% url 'user:user-logout' %}">Cerrar Sesión</a></li>
                        {% else %}
                        <li class="nav-item"><a class="btn btn-primary" href="{% url 'user:user-login' %}">Iniciar Sesion</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>                  
        </nav>
        <!-- Page Header-->
        <header class="masthead" style="background-image: url({% static 'home/assets/img/popcorn_background.jpg' %});">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>Nebula Blog</h1>
                            <span class="subheading">El blog de tus peliculas y series favoritas</span>
                            {% if user.is_authenticated %}
                            <div class="text-center">
                                <p>Bienvenido {{ user.username }}</p>
                                <img height="160px" src="{{url}}" alt="">
                            </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                
                {% block changingContent %}

                {% endblock %}
                
            </div>
        </div>
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="https://www.instagram.com/agustin_2799/">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-instagram fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="https://github.com/AGUS2799">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="https://www.linkedin.com/in/agustin-pe%C3%B1a-480161208/">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-linkedin fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        {% if user.is_authenticated %}
                        <div class="text-center">
                            {% if user.is_superuser %}
                                <p style="color: rgb(100, 49, 49)" >SuperUser</p>
                            {% else %}
                                <p style="color: rgb(100, 49, 49)" >Not SuperUser</p>
                            {%endif%}
                        {% endif %}    
                        </div>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2022</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'home/js/scripts.js' %}"></script>
    </body>
</html>

pro_final/home/templates/home/index.html
<!DOCTYPE html>
<html lang="es">
    <head>
        {% load static %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Nebula Blog </title>
        <link rel="icon" type="image/x-icon" href="{% static 'home/assets/palomitas-de-maiz.png' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'home/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'home:Home' %}"> Nebula Blog</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'home:Home' %}">Inicio</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'home:about' %}">Sobre mí</a></li>
                        {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'movies:movies-list' %}">Peliculas</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'series:series-list' %}">Series</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'perfil:perfil' user.id %}">Perfil</a></li>
                        <li><a class="btn btn-secondary" href="{% url 'user:user-logout' %}">Cerrar Sesión</a></li>
                        {% else %}
                        <li class="nav-item"><a class="btn btn-primary" href="{% url 'user:user-login' %}">Iniciar Sesion</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>                  
        </nav>
        <!-- Page Header-->
        <header class="masthead" style="background-image: url({% static 'home/assets/img/popcorn_background.jpg' %});">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>Nebula Blog</h1>
                            <span class="subheading">El blog de tus peliculas y series favoritas</span>
                            {% if user.is_authenticated %}
                            <div class="text-center">
                                <p>Bienvenido {{ user.username }}</p>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                
                {% block changingContent %}

                {% endblock %}
                
            </div>
        </div>
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="https://www.instagram.com/agustin_2799/">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-instagram fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="https://github.com/AGUS2799">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="https://www.linkedin.com/in/agustin-pe%C3%B1a-480161208/">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-linkedin fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        {% if user.is_authenticated %}
                        <div class="text-center">
                            {% if user.is_superuser %}
                                <p style="color: rgb(100, 49, 49)" >SuperUser</p>
                            {% else %}
                                <p style="color: rgb(100, 49, 49)" >Not SuperUser</p>
                            {%endif%}
                        </div>
                        {% endif %}
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2022</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'home/js/scripts.js' %}"></script>
    </body>
</html>