pro_final/home/urls.py
from django.contrib import admin
from django.urls import path
from home import views


app_name='home'
urlpatterns = [
    path('',views.home, name='Home'),
    path('about/',views.about, name='about'),
]

pro_final/pro_final/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('movies/', include('movies.urls')),
    path('user/', include('user.urls')),
    path('perfil/', include('perfil.urls')),
    path('series/', include('series.urls')),
    ]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pro_final/series/urls.py
from django.urls import path

from series import views


app_name='series'
urlpatterns = [
    path('series/', views.SeriesListView.as_view(), name='series-list'),
    path('series/add/', views.SeriesCreateView.as_view(), name='series-add'),
    path('series/<int:pk>/detail', views.SeriesDetailView.as_view(), name='series-detail'),
    path('series/<int:pk>/update', views.SeriesUpdateView.as_view(), name='series-update'),
    path('series/<int:pk>/delete', views.SeriesDeleteView.as_view(), name='series-delete'),
    path('search', views.search, name='search'),
    path('series/<int:pk>/comment/', views.AddCommentView.as_view(), name='add-comment'),
]

pro_final/series/models.py
from django.db import models

# Create your models here.
class Series(models.Model):
    name = models.CharField(max_length=40)
    release_date = models.DateField()
    director_name = models.CharField(max_length=40)
    description = models.TextField(blank= True, null=True)

pro_final/series/forms.py
from django import forms
from django.forms import ModelForm
from movies.models import Comment

class SeriesForm(forms.Form):
    name = forms.CharField(max_length=40, label='Nombre')
    release_data = forms.DateField(
        label='Fecha de Entrega',
        widget=forms.TextInput(attrs={'placeholder': 'yyyy-mm-dd'},)
    )
    director_name = forms.CharField(max_length=40, label='Nombre del director')
    description = forms.CharField(max_length=100, label='Descripción')

pro_final/series/views.py
from django.shortcuts import render

# Create your views here.
from venv import create
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from series.models import Series
from movies.models import Comment
from movies.forms import CommentForm



# Create your views here.
class SeriesListView(ListView):
    model = Series
    template_name = "Series/Series_list.html"


def search(request):
    if request.method == "POST":
        searched = request.POST['searched']
        series = Series.objects.filter(name__contains=searched)
    
        return render(
            request=request,
            context={'searched': searched, 'series': series},
            template_name="series/series_search.html",
        )
    else:
        return render(
            request=request,
            context={},
            template_name="series/series_search.html",
        )

class SeriesDetailView(DetailView):
    model = Series
    template_name = "Series/Series_detail.html"
    fields = ['name', 'release_date', 'director_name', 'description']
    


class SeriesCreateView(LoginRequiredMixin, CreateView):
    model = Series
    success_url = reverse_lazy('series:series-list')
    fields = ['name', 'release_date', 'director_name', 'description']


class SeriesUpdateView(LoginRequiredMixin, UpdateView):
    model = Series
    success_url = reverse_lazy('series:series-list')
    fields = ['name', 'release_date', 'director_name', 'description']


class SeriesDeleteView(LoginRequiredMixin, DeleteView):
    model = Series
    success_url = reverse_lazy('series:series-list')

class AddCommentView(LoginRequiredMixin, CreateView):
    model = Comment
    form_class = CommentForm
    template_name = 'series/add_comment.html'
    success_url = reverse_lazy('series:series-list')
    

pro_final/series/templates/series/add_comment.html
{% extends "home/index.html" %}
{% load static %}

{% block changingContent %}
<h1>Agregar comantario</h1>
<br><br>
<div>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-primary" value="Comentar" />
    </form>
</div>
{% endblock %}

pro_final/series/templates/series/series_confirm_delete.html
{% extends "home/index.html" %}
{% load static %}

{% block changingContent %}

<h2>Eliminar Serie</h2>
<hr></hr>

<p>Estás seguro de eliminar la serie: {{ series.name }}?</p>

<form action="" method="POST">
    {% csrf_token %}
    <input class="btn btn-primary text-uppercase" type="submit" value="Si, eliminar.">
    <a class="btn btn-primary text-uppercase" href="{% url 'series:series-list' %}" >Cancelar</a>
</form>

{% endblock %}

pro_final/series/templates/series/series_detail.html
{% extends "home/index.html" %}
{% load static %}

{% block changingContent %}

<h2>Detalles de la Serie</h2>
<hr></hr>
<p><h3>Nombre: {{ series.name }}</h3></p>
<p><h3>fecha de estreno: {{ series.release_date }}</h3></p>
<p><h3>Nombre del director: {{ series.director_name }}</h3></p>
<h4>Descripción:</h4>
<p><textarea readonly rows="7" cols="90" >{{ series.description }}</textarea></p>
<p><a class="btn btn-primary" href="{% url 'series:add-comment' series.id %}">Comentar</a></p>
<div>
    <div>
        <h3>Comentarios</h3>
    </div>
</div>
<p><a class="btn btn-primary" href="{% url 'series:series-list' %}">Regresar a la lista de series</a></p>

{% endblock %}

pro_final/series/templates/series/series_form.html
{% extends "home/index.html" %}
{% load static %}

{% block changingContent %}
<h2>Formulario para guardar/editar Serie</h2>
<hr></hr>

<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-primary" value="Guardar Serie" />
</form>
{% endblock %}

pro_final/series/templates/series/series_list.html
{% extends "home/index.html" %}
{% load static %}

{% block changingContent %}
<h1>Series</h1>
{% if user.is_superuser %}
<a class="btn btn-primary text-uppercase" href="{% url 'series:series-add' %}">Agregar Serie</a>
{% endif %}
<hr></hr>
<form action="{% url 'series:search' %}" method="POST">
    <div>
        {% csrf_token %}
        <input type="search" name="searched" placeholder="Buscar Peiculas">
        <button type="submit">Buscar</button>
        <a style="color: blue" href="{% url 'series:series-list' %}"><i class="fa fa-undo"></i></a>
    </div>

</form>

<ul>
    {% if series_list %}
    {% for series in series_list %}
    <li>
        {{series.name}}
        (
            <a href="{% url 'series:series-detail' series.id %}">
                <i class="fa fa-eye" style="color: rgb(0, 0, 255);"> </i>
            </a>
        
        |
        {% if user.is_superuser %}
        <a href="{% url 'series:series-update' series.id %}">
            <i class="fa fa-pencil" style="color: rgb(0, 0, 190);"> </i>
        </a>
        |
        <a href="{% url 'series:series-delete' series.id %}">
            <i class="fa fa-trash" style="color: rgb(214, 6, 6);"> </i>
        </a>
        {% endif %}
        )
    </li>
    {% endfor %}
    {% else %}
        <p>No hay niguna Serie cargada</p>
    {% endif %}
</ul>

{% endblock %}

pro_final/series/templates/series/series_search.html
{% extends "home/index.html" %}
{% load static %}

{% block changingContent %}
    <div>
        {% if searched %}
            <h1>Estos son los resultados de "{{ searched }}"</h1>
            <br><br>
            <ul>
                {% for serie in series %}
                <li>
                    {{serie.name}}
                    (
                        <a href="{% url 'series:series-detail' serie.id %}">
                            <i class="fa fa-eye" style="color: rgb(0, 0, 255);"> </i>
                        </a>
                {% if user.is_superuser %}
                |
                <a href="{% url 'series:series-update' serie.id %}">
                    <i class="fa fa-pencil" style="color: rgb(0, 0, 190);"> </i>
                </a>
                |
                <a href="{% url 'series:series-delete' serie.id %}">
                    <i class="fa fa-trash" style="color: rgb(214, 6, 6);"> </i>
                </a>
                {% endif %}
                )
                </li>
                {% endfor %}
            </ul>
            <p class="btn btn-secondary"><a href="{% url 'series:series-list'%}">Regresar..</a></p>
        {% else %}
            <h1>No buscaste nada</h1>
            <p class="btn btn-secondary"><a href="{% url 'series:series-list'%}">Regresar..</a></p>
        {% endif %}
    </div>
{% endblock %}